//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Id_Articulo { get; set; }
        public string Descripcion { get; set; }
        public string Marca { get; set; }
        public Nullable<double> Costo { get; set; }
        public Nullable<double> Precio_Unitario { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public Nullable<System.DateTime> Vencimiento { get; set; }
    }
}
