//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id { get; set; }
        public Nullable<int> NroFactura { get; set; }
        public Nullable<int> Timbrado { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> TipoPago { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<double> MontoTotal { get; set; }
    }
}
