//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public int CodProveedor { get; set; }
        public string Nombre { get; set; }
        public string NroDocumento { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string PersonaContacto { get; set; }
    }
}
